name: Docker build

on:
  pull_request:
    branches: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Docker build
      run: docker build -t coiled/default .
    