name: Build and deploy tags

on:
  push:
    tags: "*"

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Docker login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username $${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Docker build
      run: docker build -t coiled/default .
    
    - name: Get tag
      id: get_tag
      run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
    
    - name: Docker push tag
      run: |
        docker tag coiled/default coiled/default:${{ steps.get_tag.outputs.TAG }}
        docker push coiled/default:${{ steps.get_tag.outputs.TAG }}
